# Generated by Django 5.2.8 on 2025-11-24 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('Pdf', 'Pdf'), ('Article', 'Article'), ('Video', 'Video')], max_length=10)),
                ('category', models.CharField(max_length=100)),
                ('difficulty', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], max_length=12)),
                ('image', models.ImageField(blank=True, null=True, upload_to='resources/images/')),
                ('link', models.URLField()),
                ('description', models.TextField()),
                ('rating', models.FloatField(default=0.0)),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
