# Generated by Django 5.2.8 on 2025-11-24 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_gender'),
        ('resources', '0002_resources_counsellor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='Counsellor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.counsellor'),
        ),
    ]
