# Generated by Django 5.2.8 on 2025-11-24 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_alter_resources_counsellor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resources',
            options={'ordering': ['-featured', '-rating', '-created_at']},
        ),
        migrations.AddField(
            model_name='resources',
            name='duration',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='resources',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='resources',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=12),
        ),
        migrations.AlterField(
            model_name='resources',
            name='type',
            field=models.CharField(choices=[('Article', 'Article'), ('Video', 'Video'), ('PDF', 'PDF'), ('Audio', 'Audio')], max_length=10),
        ),
    ]
