# Generated by Django 5.2.8 on 2025-11-24 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_alter_resources_options_resources_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='image',
            field=models.ImageField(upload_to='resources/images/'),
        ),
    ]
